### ISSUE TITLE
Error on bundle install

### ISSUE THREAD

**Issue by adrianoprospero** [phlegx/redmine_gitlab_hook#32]
Hi,
I'm trying to install the plugin, but I always get the following error on bundle install:

> Using bundler 1.14.3
> Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native
> extension.
> 
>         /usr/bin/ruby1.9.1 extconf.rb
> /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such
> file -- mkmf (LoadError)
>         from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
>         from extconf.rb:1:in `<main>'
> 
> 
> Gem files will remain installed in /var/lib/gems/1.9.1/gems/json-2.0.3 for
> inspection.
> Results logged to
> /var/lib/gems/1.9.1/gems/json-2.0.3/ext/json/ext/generator/gem_make.out
> 
> An error occurred while installing json (2.0.3), and Bundler cannot
> continue.
> Make sure that `gem install json -v '2.0.3'` succeeds before bundling.
> 

When I try to install this json gem, it also doesn't work. Isn't me doing anything wrong?

Thanks in advance.

**Comment by adrianoprospero** [comment]
Got to solve it installing ruby-dev through apt-get.
