### ISSUE TITLE
TypeError (no implicit conversion of nil into String)

### ISSUE THREAD

**Issue by ghenry** [phlegx/redmine_gitlab_hook#50]
Hi, 

When I test a push from GitLab I keep getting:

```
TypeError (no implicit conversion of nil into String):
  
plugins/redmine_gitlab_hook/app/controllers/gitlab_hook_controller.rb:162:in `join'
plugins/redmine_gitlab_hook/app/controllers/gitlab_hook_controller.rb:162:in `create_repository'
plugins/redmine_gitlab_hook/app/controllers/gitlab_hook_controller.rb:135:in `find_repository'
plugins/redmine_gitlab_hook/app/controllers/gitlab_hook_controller.rb:10:in `in
```

**Comment by ghenry** [comment]
Looking at https://github.com/phlegx/redmine_gitlab_hook/blob/master/app/controllers/gitlab_hook_controller.rb#L162 it seems I need to provide repository_name in my GitLab link. Working now.
